name: milvus
services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd:/etcd
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: etcd -advertise-client-urls=http://100.106.39.74:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    networks:
      - services
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:latest
    command: [ "milvus", "run", "standalone" ]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: 100.106.39.74:9000
      MINIO_ACCESS_KEY_ID: ghost
      MINIO_SECRET_ACCESS_KEY: Tabi9982
      MINIO_BUCKET_NAME: milvus
    volumes:
      - milvus:/var/lib/milvus
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://100.106.39.74:9091/health" ]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
    restart: unless-stopped
    networks:
      - services
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  attu:
    container_name: milvus-attu
    image: zilliz/attu:latest
    environment:
      MILVUS_URL: 100.106.39.74:19530
    ports:
      - "8770:3000"
    restart: unless-stopped
    depends_on:
      - "standalone"
    networks:
      - services
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  milvus:
    name: milvus_data
  etcd:
    name: etcd_data

networks:
  services:
    external: true
