name: mongodb
services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    user: root:root
    volumes:
      - mongo:/data/db:rw,z
      - config:/data/configdb:rw,z
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    networks:
      - services
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  mongo:
    name: mongo_data

  config:
    name: mongo_config

networks:
  services:
    external: true
