name: portainer
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - services
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  portainer_agent:
    container_name: portainer_agent
    image: portainer/agent:latest
    ports:
      - 9444:9444
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    environment:
      - AGENT_PORT=9444
    networks:
      - services
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  data:


networks:
  services:
    name: services
    driver: bridge
