name: minio
services:
  minio:
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
      - "8021:8021"
      - "30000-30100:30000-30100"
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001" --ftp="address=:8021" --ftp="passive-port-range=30000-30100"
    environment:
      - MINIO_ROOT_USER=ghost
      - MINIO_ROOT_PASSWORD=Tabi9982
    restart: always
    user: root:root
    volumes:
      - minio:/data:rw,z
      # - /home/thinh/.minio/certs:/root/.minio/certs:rw,z
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - services
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  minio:
    name: minio_data

networks:
  services:
    external: true
