services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: always
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - services
  kafka:
    image: confluentinc/cp-kafka:7.4.3
    hostname: becamex
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      # KAFKA_ADVERTISED_HOSTS: 10.71.0.199
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://100.93.170.37:9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 1000
      KAFKA_LOG_RETENTION_MINUTES : 10
    restart: always
    networks:
      - services

networks:
  services:
    external: true