name: postgres
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    user: root:root
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    networks:
      - services
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=becaiVMS


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - services
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  postgres-data:
    name: postgres_data
  pgadmin-data:
    name: pgadmin_data

networks:
  services:
    external: true
