name: redis
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - services
    volumes:
      - redis:/data:rw,z
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  redis:
    name: redis_data

networks:
  services:
    external: true
